# Generated by Django 4.2.25 on 2025-11-04 17:10

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "employee_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Personalnummer"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin (Vollzugriff + Erweiterungen)"),
                            ("manager", "Manager (Vollzugriff ohne Erweiterungen)"),
                            ("staff", "Personal (Standard)"),
                        ],
                        default="staff",
                        max_length=20,
                        verbose_name="Rolle",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefon"
                    ),
                ),
                (
                    "is_active_employee",
                    models.BooleanField(
                        default=True, verbose_name="Aktiver Mitarbeiter"
                    ),
                ),
                (
                    "can_simultaneous_login",
                    models.BooleanField(
                        default=True, verbose_name="Simultanes Anmelden erlaubt"
                    ),
                ),
                (
                    "last_check_in",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Letzter Check-in"
                    ),
                ),
                (
                    "last_check_out",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Letzter Check-out"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mitarbeiter",
                "verbose_name_plural": "Mitarbeiter",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AnalyticsSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateField(unique=True, verbose_name="Snapshot-Datum"),
                ),
                (
                    "total_reservations",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Gesamt Reservierungen"
                    ),
                ),
                (
                    "confirmed_reservations",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Bestätigte Reservierungen"
                    ),
                ),
                (
                    "cancelled_reservations",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Stornierte Reservierungen"
                    ),
                ),
                (
                    "no_show_count",
                    models.PositiveIntegerField(default=0, verbose_name="No-Shows"),
                ),
                (
                    "average_occupancy_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Durchschnittl. Auslastung %",
                    ),
                ),
                (
                    "peak_occupancy_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Haupt-Auslastungszeit"
                    ),
                ),
                (
                    "total_guests_served",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Gesamt bediente Gäste"
                    ),
                ),
                (
                    "average_party_size",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=4,
                        verbose_name="Durchschnittl. Gruppengröße",
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Gesamtumsatz",
                    ),
                ),
                (
                    "ai_insights",
                    models.JSONField(
                        blank=True, default=list, verbose_name="KI-Insights"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Analytics-Snapshot",
                "verbose_name_plural": "Analytics-Snapshots",
                "ordering": ["-snapshot_date"],
            },
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Bereichsname"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Beschreibung"
                    ),
                ),
                (
                    "total_capacity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Gesamtkapazität"
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        default="#3B82F6", max_length=7, verbose_name="Farbcode"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "allows_combinations",
                    models.BooleanField(
                        default=True, verbose_name="Tischkombinationen erlaubt"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bereich",
                "verbose_name_plural": "Bereiche",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Titel"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_conversations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Mitarbeiter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat-Konversation",
                "verbose_name_plural": "Chat-Konversationen",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="Vorname"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Nachname"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Telefonnummer"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="E-Mail"
                    ),
                ),
                (
                    "allergies",
                    models.TextField(blank=True, null=True, verbose_name="Allergien"),
                ),
                (
                    "special_requests",
                    models.TextField(
                        blank=True, null=True, verbose_name="Besondere Wünsche"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notizen/Präferenzen"
                    ),
                ),
                (
                    "gdpr_consent",
                    models.BooleanField(
                        default=False, verbose_name="DSGVO-Einwilligung"
                    ),
                ),
                (
                    "gdpr_consent_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="DSGVO-Einwilligung Datum"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Gast",
                "verbose_name_plural": "Gäste",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="PensionGuest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "salutation",
                    models.CharField(
                        choices=[
                            ("herr", "Herr"),
                            ("frau", "Frau"),
                            ("divers", "Divers"),
                        ],
                        max_length=20,
                        verbose_name="Anrede",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="Vorname"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Nachname"),
                ),
                ("birth_date", models.DateField(verbose_name="Geburtsdatum")),
                (
                    "nationality",
                    models.CharField(max_length=50, verbose_name="Staatsangehörigkeit"),
                ),
                ("street", models.CharField(max_length=200, verbose_name="Straße")),
                (
                    "house_number",
                    models.CharField(max_length=10, verbose_name="Hausnummer"),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=10, verbose_name="Postleitzahl"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Ort")),
                ("country", models.CharField(max_length=50, verbose_name="Land")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("id_card", "Personalausweis"),
                            ("passport", "Reisepass"),
                            ("driving_license", "Führerschein"),
                        ],
                        max_length=20,
                        verbose_name="Dokumenttyp",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(max_length=50, verbose_name="Dokumentnummer"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="E-Mail"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefon"
                    ),
                ),
                (
                    "gdpr_consent",
                    models.BooleanField(
                        default=False, verbose_name="DSGVO-Einwilligung"
                    ),
                ),
                (
                    "gdpr_consent_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="DSGVO-Einwilligung Datum"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pensionsgast",
                "verbose_name_plural": "Pensionsgäste",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=200, verbose_name="Firmenname"),
                ),
                (
                    "company_street",
                    models.CharField(max_length=200, verbose_name="Straße"),
                ),
                (
                    "company_postal_code",
                    models.CharField(max_length=10, verbose_name="PLZ"),
                ),
                ("company_city", models.CharField(max_length=100, verbose_name="Ort")),
                (
                    "company_phone",
                    models.CharField(max_length=20, verbose_name="Telefon"),
                ),
                (
                    "company_email",
                    models.EmailField(max_length=254, verbose_name="E-Mail"),
                ),
                (
                    "company_website",
                    models.URLField(blank=True, null=True, verbose_name="Website"),
                ),
                (
                    "company_logo_url",
                    models.URLField(blank=True, null=True, verbose_name="Logo URL"),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Steuernummer",
                    ),
                ),
                (
                    "vat_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="USt-ID"
                    ),
                ),
                (
                    "default_reservation_duration",
                    models.PositiveIntegerField(
                        default=120, verbose_name="Standard Reservierungsdauer (Min)"
                    ),
                ),
                (
                    "reservation_lead_time",
                    models.PositiveIntegerField(
                        default=90, verbose_name="Vorlaufzeit für Reservierungen (Tage)"
                    ),
                ),
                (
                    "max_guests_per_reservation",
                    models.PositiveIntegerField(
                        default=20, verbose_name="Max. Gäste pro Reservierung"
                    ),
                ),
                (
                    "tourist_tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.5,
                        max_digits=5,
                        verbose_name="Kurtaxe pro Nacht",
                    ),
                ),
                (
                    "tourist_tax_enabled",
                    models.BooleanField(default=True, verbose_name="Kurtaxe aktiv"),
                ),
                (
                    "auto_logout_hours",
                    models.PositiveIntegerField(
                        default=24, verbose_name="Auto-Logout nach (Stunden)"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Europe/Berlin", max_length=50, verbose_name="Zeitzone"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="de", max_length=10, verbose_name="Sprache"
                    ),
                ),
                (
                    "backup_frequency_hours",
                    models.PositiveIntegerField(
                        default=8, verbose_name="Backup-Frequenz (Stunden)"
                    ),
                ),
                (
                    "last_backup",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Letztes Backup"
                    ),
                ),
                (
                    "smtp_host",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="SMTP Server",
                    ),
                ),
                (
                    "smtp_port",
                    models.PositiveIntegerField(default=587, verbose_name="SMTP Port"),
                ),
                (
                    "smtp_username",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="SMTP Benutzername",
                    ),
                ),
                (
                    "smtp_password",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="SMTP Passwort",
                    ),
                ),
                (
                    "smtp_use_tls",
                    models.BooleanField(
                        default=True, verbose_name="SMTP TLS verwenden"
                    ),
                ),
                (
                    "email_from_address",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Absender E-Mail",
                    ),
                ),
                (
                    "gdpr_consent_text",
                    models.TextField(
                        default="Ich stimme der Verarbeitung meiner personenbezogenen Daten gemäß der Datenschutzerklärung zu.",
                        verbose_name="DSGVO-Einwilligungstext",
                    ),
                ),
                (
                    "gdpr_guest_retention_months",
                    models.PositiveIntegerField(
                        default=24, verbose_name="Gäste-Daten Aufbewahrung (Monate)"
                    ),
                ),
                (
                    "gdpr_reservation_retention_months",
                    models.PositiveIntegerField(
                        default=12,
                        verbose_name="Reservierungs-Daten Aufbewahrung (Monate)",
                    ),
                ),
                (
                    "gdpr_timetracking_retention_years",
                    models.PositiveIntegerField(
                        default=10,
                        verbose_name="Zeiterfassungs-Daten Aufbewahrung (Jahre)",
                    ),
                ),
                (
                    "opening_hours",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Öffnungszeiten"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Systemeinstellung",
                "verbose_name_plural": "Systemeinstellungen",
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "table_number",
                    models.CharField(max_length=10, verbose_name="Tischnummer"),
                ),
                ("capacity", models.PositiveIntegerField(verbose_name="Kapazität")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Verfügbar"),
                            ("occupied", "Besetzt"),
                            ("reserved", "Reserviert"),
                            ("out_of_service", "Außer Betrieb"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_reservable",
                    models.BooleanField(default=True, verbose_name="Reservierbar"),
                ),
                (
                    "is_combinable",
                    models.BooleanField(default=False, verbose_name="Kombinierbar"),
                ),
                (
                    "position_x",
                    models.IntegerField(default=0, verbose_name="Position X"),
                ),
                (
                    "position_y",
                    models.IntegerField(default=0, verbose_name="Position Y"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notizen"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="app_core.area",
                        verbose_name="Bereich",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tisch",
                "verbose_name_plural": "Tische",
                "ordering": ["area__name", "table_number"],
                "unique_together": {("area", "table_number")},
            },
        ),
        migrations.CreateModel(
            name="TimeTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("check_in", models.DateTimeField(verbose_name="Check-in")),
                (
                    "check_out",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Check-out"
                    ),
                ),
                (
                    "auto_logout",
                    models.BooleanField(default=False, verbose_name="Auto-Logout"),
                ),
                (
                    "manual_correction",
                    models.BooleanField(
                        default=False, verbose_name="Manuelle Korrektur"
                    ),
                ),
                (
                    "correction_note",
                    models.TextField(
                        blank=True, null=True, verbose_name="Korrektur Notiz"
                    ),
                ),
                (
                    "total_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Gesamtstunden",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Mitarbeiter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zeiterfassung",
                "verbose_name_plural": "Zeiterfassungen",
                "ordering": ["-check_in"],
            },
        ),
        migrations.CreateModel(
            name="TableCombination",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Kombinationsname"),
                ),
                (
                    "total_capacity",
                    models.PositiveIntegerField(verbose_name="Gesamtkapazität"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tables",
                    models.ManyToManyField(
                        related_name="combinations",
                        to="app_core.table",
                        verbose_name="Tische",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tischkombination",
                "verbose_name_plural": "Tischkombinationen",
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reservation_time",
                    models.DateTimeField(verbose_name="Reservierungszeitpunkt"),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=120, verbose_name="Dauer (Minuten)"
                    ),
                ),
                (
                    "number_of_guests",
                    models.PositiveIntegerField(verbose_name="Anzahl Gäste"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_confirmation", "Bestätigung ausstehend"),
                            ("confirmed", "Bestätigt"),
                            ("checked_in", "Eingecheckt"),
                            ("checked_out", "Ausgecheckt"),
                            ("cancelled_by_guest", "Storniert (Gast)"),
                            ("cancelled_by_restaurant", "Storniert (Restaurant)"),
                            ("completed", "Abgeschlossen"),
                            ("no_show", "Nicht erschienen"),
                        ],
                        default="pending_confirmation",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Bar"),
                            ("ec", "EC-Karte"),
                            ("credit_card", "Kreditkarte"),
                            ("invoice", "Rechnung"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Zahlungsart",
                    ),
                ),
                (
                    "check_in_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Check-in Zeit"
                    ),
                ),
                (
                    "check_out_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Check-out Zeit"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Spezielle Wünsche"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="app_core.guest",
                        verbose_name="Gast",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="app_core.table",
                        verbose_name="Tisch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reservierung",
                "verbose_name_plural": "Reservierungen",
                "ordering": ["-reservation_time"],
            },
        ),
        migrations.CreateModel(
            name="RegistrationForm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("arrival_date", models.DateField(verbose_name="Anreisedatum")),
                ("departure_date", models.DateField(verbose_name="Abreisedatum")),
                (
                    "room_number",
                    models.CharField(max_length=10, verbose_name="Zimmernummer"),
                ),
                (
                    "travel_purpose",
                    models.CharField(
                        choices=[("private", "Privat"), ("business", "Geschäftlich")],
                        max_length=20,
                        verbose_name="Reisezweck",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Firmenname"
                    ),
                ),
                (
                    "company_address",
                    models.TextField(
                        blank=True, null=True, verbose_name="Firmenadresse"
                    ),
                ),
                (
                    "tourist_tax_required",
                    models.BooleanField(default=True, verbose_name="Kurtaxepflichtig"),
                ),
                (
                    "tourist_tax_exemption_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Befreiungsgrund Kurtaxe"
                    ),
                ),
                (
                    "tourist_tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Kurtaxe Betrag",
                    ),
                ),
                (
                    "breakfast_included",
                    models.BooleanField(
                        default=False, verbose_name="Frühstück inklusive"
                    ),
                ),
                (
                    "breakfast_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Frühstück Preis",
                    ),
                ),
                (
                    "room_price_per_night",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Zimmerpreis pro Nacht",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Gesamtsumme",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Bar"),
                            ("ec", "EC-Karte"),
                            ("credit_card", "Kreditkarte"),
                            ("invoice", "Rechnung"),
                        ],
                        max_length=20,
                        verbose_name="Zahlungsart",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Ausstehend"),
                            ("paid", "Bezahlt"),
                            ("partially_paid", "Teilweise bezahlt"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Zahlungsstatus",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("confirmed", "Bestätigt"),
                            ("checked_in", "Eingecheckt"),
                            ("checked_out", "Ausgecheckt"),
                            ("cancelled", "Storniert"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "exported_to_city",
                    models.BooleanField(
                        default=False, verbose_name="An Stadt exportiert"
                    ),
                ),
                (
                    "export_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Exportdatum"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notizen"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="app_core.pensionguest",
                        verbose_name="Gast",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meldeschein",
                "verbose_name_plural": "Meldescheine",
                "ordering": ["-arrival_date"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "Benutzer"),
                            ("assistant", "Assistent"),
                            ("system", "System"),
                        ],
                        max_length=20,
                        verbose_name="Rolle",
                    ),
                ),
                ("content", models.TextField(verbose_name="Nachricht")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadaten"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="app_core.chatconversation",
                        verbose_name="Konversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat-Nachricht",
                "verbose_name_plural": "Chat-Nachrichten",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SpecialOpeningHours",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(verbose_name="Datum")),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Beschreibung"),
                ),
                (
                    "is_closed",
                    models.BooleanField(default=False, verbose_name="Geschlossen"),
                ),
                (
                    "open_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Öffnungszeit"
                    ),
                ),
                (
                    "close_time",
                    models.TimeField(blank=True, null=True, verbose_name="Schließzeit"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_opening_hours",
                        to="app_core.area",
                        verbose_name="Bereich",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sonder-Öffnungszeit",
                "verbose_name_plural": "Sonder-Öffnungszeiten",
                "ordering": ["date"],
                "unique_together": {("area", "date")},
            },
        ),
        migrations.CreateModel(
            name="OpeningHours",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Montag"),
                            (1, "Dienstag"),
                            (2, "Mittwoch"),
                            (3, "Donnerstag"),
                            (4, "Freitag"),
                            (5, "Samstag"),
                            (6, "Sonntag"),
                        ],
                        verbose_name="Wochentag",
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(default=False, verbose_name="Geschlossen"),
                ),
                (
                    "open_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Öffnungszeit"
                    ),
                ),
                (
                    "close_time",
                    models.TimeField(blank=True, null=True, verbose_name="Schließzeit"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_hours",
                        to="app_core.area",
                        verbose_name="Bereich",
                    ),
                ),
            ],
            options={
                "verbose_name": "Öffnungszeit",
                "verbose_name_plural": "Öffnungszeiten",
                "ordering": ["area", "weekday"],
                "unique_together": {("area", "weekday")},
            },
        ),
        migrations.CreateModel(
            name="CapacityRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(verbose_name="Datum")),
                ("time_slot", models.TimeField(verbose_name="Zeitslot")),
                (
                    "predicted_occupancy",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Vorhergesagte Auslastung %",
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Konfidenz-Score"
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("increase_staff", "Personal aufstocken"),
                            ("reduce_staff", "Personal reduzieren"),
                            ("optimize_tables", "Tische optimieren"),
                            (
                                "accept_more_reservations",
                                "Mehr Reservierungen annehmen",
                            ),
                            ("limit_reservations", "Reservierungen begrenzen"),
                            ("normal_operations", "Normaler Betrieb"),
                        ],
                        max_length=30,
                        verbose_name="Empfehlungstyp",
                    ),
                ),
                (
                    "recommendation_text",
                    models.TextField(verbose_name="Empfehlungstext"),
                ),
                (
                    "based_on_data",
                    models.JSONField(default=dict, verbose_name="Datenbasis"),
                ),
                (
                    "is_applied",
                    models.BooleanField(default=False, verbose_name="Angewendet"),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Angewendet am"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capacity_recommendations",
                        to="app_core.area",
                        verbose_name="Bereich",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kapazitäts-Empfehlung",
                "verbose_name_plural": "Kapazitäts-Empfehlungen",
                "ordering": ["-date", "-time_slot"],
                "unique_together": {("date", "time_slot", "area")},
            },
        ),
    ]
