# Generated by Django (simulated)
#
# This is a placeholder for an actual migration file.
# In a real scenario, `python manage.py makemigrations app_core` would generate this.

from django.db import migrations, models
import django.db.models.deletion
import uuid

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Bereichsname')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bereich',
                'verbose_name_plural': 'Bereiche',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nachname')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Telefonnummer')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-Mail')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notizen/Präferenzen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gast',
                'verbose_name_plural': 'Gäste',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_number', models.CharField(max_length=10, verbose_name='Tischnummer')),
                ('capacity', models.PositiveIntegerField(verbose_name='Kapazität')),
                ('status', models.CharField(choices=[('available', 'Verfügbar'), ('occupied', 'Besetzt'), ('reserved', 'Reserviert'), ('out_of_service', 'Außer Betrieb')], default='available', max_length=20, verbose_name='Status')),
                ('is_reservable', models.BooleanField(default=True, verbose_name='Reservierbar')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='app_core.area', verbose_name='Bereich')),
            ],
            options={
                'verbose_name': 'Tisch',
                'verbose_name_plural': 'Tische',
                'ordering': ['area__name', 'table_number'],
                'unique_together': {('area', 'table_number')},
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reservation_time', models.DateTimeField(verbose_name='Reservierungszeitpunkt')),
                ('duration_minutes', models.PositiveIntegerField(default=120, verbose_name='Dauer (Minuten)')),
                ('number_of_guests', models.PositiveIntegerField(verbose_name='Anzahl Gäste')),
                ('status', models.CharField(choices=[('pending_confirmation', 'Bestätigung ausstehend'), ('confirmed', 'Bestätigt'), ('cancelled_by_guest', 'Storniert (Gast)'), ('cancelled_by_restaurant', 'Storniert (Restaurant)'), ('completed', 'Abgeschlossen'), ('no_show', 'Nicht erschienen')], default='pending_confirmation', max_length=30, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Spezielle Wünsche')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='app_core.guest', verbose_name='Gast')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='app_core.table', verbose_name='Tisch')),
            ],
            options={
                'verbose_name': 'Reservierung',
                'verbose_name_plural': 'Reservierungen',
                'ordering': ['-reservation_time'],
            },
        ),
    ]
