# Generated by Django 4.2.30 on 2026-09-25 05:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("app_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="Vorname"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Nachname"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Telefonnummer"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="E-Mail"
                    ),
                ),
                (
                    "requested_time",
                    models.DateTimeField(verbose_name="Gewünschter Zeitpunkt"),
                ),
                (
                    "number_of_guests",
                    models.PositiveIntegerField(verbose_name="Anzahl Gäste"),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Nachricht/Sonderwünsche"
                    ),
                ),
                (
                    "source_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Quell-IP"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Eingegangen am"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Prüfung ausstehend"),
                            ("approved", "Freigegeben"),
                            ("rejected", "Abgelehnt"),
                            ("auto_approved", "Automatisch freigegeben"),
                        ],
                        default="pending_review",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "risk_score",
                    models.IntegerField(default=0, verbose_name="Risiko-Score"),
                ),
                (
                    "risk_reasons",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Risiko-Gründe"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Geprüft am"
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_requests",
                        to="app_core.reservation",
                        verbose_name="Erstellte Reservierung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reservierungsanfrage",
                "verbose_name_plural": "Reservierungsanfragen",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
