# Generated by Django 4.2.30 on 2026-09-25 05:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_core", "0002_reservationrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="color",
            field=models.CharField(
                choices=[
                    ("blue", "Blau"),
                    ("green", "Grün"),
                    ("yellow", "Gelb"),
                    ("red", "Rot"),
                    ("purple", "Lila"),
                    ("orange", "Orange"),
                    ("pink", "Pink"),
                    ("indigo", "Indigo"),
                ],
                default="blue",
                max_length=20,
                verbose_name="Anzeigefarbe",
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="layout_height",
            field=models.PositiveIntegerField(
                default=10,
                validators=[django.core.validators.MinValueValidator(5)],
                verbose_name="Layout-Höhe (Raster)",
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="layout_width",
            field=models.PositiveIntegerField(
                default=10,
                validators=[django.core.validators.MinValueValidator(5)],
                verbose_name="Layout-Breite (Raster)",
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="location",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Lage (z. B. Erdgeschoss)"
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="rotation",
            field=models.PositiveIntegerField(default=0, verbose_name="Drehung (Grad)"),
        ),
    ]
