# Generated by Django 4.2.30 on 2026-09-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_core", "0003_area_color_area_layout_height_area_layout_width_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetracking",
            name="break_minutes",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Pause (Minuten)"
            ),
        ),
    ]
